# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/logic_monitor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/logic_monitor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/logic_monitor/CMakeFiles /mnt/d/logic_monitor/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/logic_monitor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named logic_monitor

# Build rule for target.
logic_monitor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 logic_monitor
.PHONY : logic_monitor

# fast build rule for target.
logic_monitor/fast:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/build
.PHONY : logic_monitor/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/main.cpp.s
.PHONY : main.cpp.s

src/adder64.o: src/adder64.cpp.o

.PHONY : src/adder64.o

# target to build an object file
src/adder64.cpp.o:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/adder64.cpp.o
.PHONY : src/adder64.cpp.o

src/adder64.i: src/adder64.cpp.i

.PHONY : src/adder64.i

# target to preprocess a source file
src/adder64.cpp.i:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/adder64.cpp.i
.PHONY : src/adder64.cpp.i

src/adder64.s: src/adder64.cpp.s

.PHONY : src/adder64.s

# target to generate assembly for a file
src/adder64.cpp.s:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/adder64.cpp.s
.PHONY : src/adder64.cpp.s

src/and_device.o: src/and_device.cpp.o

.PHONY : src/and_device.o

# target to build an object file
src/and_device.cpp.o:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/and_device.cpp.o
.PHONY : src/and_device.cpp.o

src/and_device.i: src/and_device.cpp.i

.PHONY : src/and_device.i

# target to preprocess a source file
src/and_device.cpp.i:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/and_device.cpp.i
.PHONY : src/and_device.cpp.i

src/and_device.s: src/and_device.cpp.s

.PHONY : src/and_device.s

# target to generate assembly for a file
src/and_device.cpp.s:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/and_device.cpp.s
.PHONY : src/and_device.cpp.s

src/and_not_device.o: src/and_not_device.cpp.o

.PHONY : src/and_not_device.o

# target to build an object file
src/and_not_device.cpp.o:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/and_not_device.cpp.o
.PHONY : src/and_not_device.cpp.o

src/and_not_device.i: src/and_not_device.cpp.i

.PHONY : src/and_not_device.i

# target to preprocess a source file
src/and_not_device.cpp.i:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/and_not_device.cpp.i
.PHONY : src/and_not_device.cpp.i

src/and_not_device.s: src/and_not_device.cpp.s

.PHONY : src/and_not_device.s

# target to generate assembly for a file
src/and_not_device.cpp.s:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/and_not_device.cpp.s
.PHONY : src/and_not_device.cpp.s

src/and_not_device3.o: src/and_not_device3.cpp.o

.PHONY : src/and_not_device3.o

# target to build an object file
src/and_not_device3.cpp.o:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/and_not_device3.cpp.o
.PHONY : src/and_not_device3.cpp.o

src/and_not_device3.i: src/and_not_device3.cpp.i

.PHONY : src/and_not_device3.i

# target to preprocess a source file
src/and_not_device3.cpp.i:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/and_not_device3.cpp.i
.PHONY : src/and_not_device3.cpp.i

src/and_not_device3.s: src/and_not_device3.cpp.s

.PHONY : src/and_not_device3.s

# target to generate assembly for a file
src/and_not_device3.cpp.s:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/and_not_device3.cpp.s
.PHONY : src/and_not_device3.cpp.s

src/and_not_device4.o: src/and_not_device4.cpp.o

.PHONY : src/and_not_device4.o

# target to build an object file
src/and_not_device4.cpp.o:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/and_not_device4.cpp.o
.PHONY : src/and_not_device4.cpp.o

src/and_not_device4.i: src/and_not_device4.cpp.i

.PHONY : src/and_not_device4.i

# target to preprocess a source file
src/and_not_device4.cpp.i:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/and_not_device4.cpp.i
.PHONY : src/and_not_device4.cpp.i

src/and_not_device4.s: src/and_not_device4.cpp.s

.PHONY : src/and_not_device4.s

# target to generate assembly for a file
src/and_not_device4.cpp.s:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/and_not_device4.cpp.s
.PHONY : src/and_not_device4.cpp.s

src/carry4.o: src/carry4.cpp.o

.PHONY : src/carry4.o

# target to build an object file
src/carry4.cpp.o:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/carry4.cpp.o
.PHONY : src/carry4.cpp.o

src/carry4.i: src/carry4.cpp.i

.PHONY : src/carry4.i

# target to preprocess a source file
src/carry4.cpp.i:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/carry4.cpp.i
.PHONY : src/carry4.cpp.i

src/carry4.s: src/carry4.cpp.s

.PHONY : src/carry4.s

# target to generate assembly for a file
src/carry4.cpp.s:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/carry4.cpp.s
.PHONY : src/carry4.cpp.s

src/carry64.o: src/carry64.cpp.o

.PHONY : src/carry64.o

# target to build an object file
src/carry64.cpp.o:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/carry64.cpp.o
.PHONY : src/carry64.cpp.o

src/carry64.i: src/carry64.cpp.i

.PHONY : src/carry64.i

# target to preprocess a source file
src/carry64.cpp.i:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/carry64.cpp.i
.PHONY : src/carry64.cpp.i

src/carry64.s: src/carry64.cpp.s

.PHONY : src/carry64.s

# target to generate assembly for a file
src/carry64.cpp.s:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/carry64.cpp.s
.PHONY : src/carry64.cpp.s

src/clock.o: src/clock.cpp.o

.PHONY : src/clock.o

# target to build an object file
src/clock.cpp.o:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/clock.cpp.o
.PHONY : src/clock.cpp.o

src/clock.i: src/clock.cpp.i

.PHONY : src/clock.i

# target to preprocess a source file
src/clock.cpp.i:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/clock.cpp.i
.PHONY : src/clock.cpp.i

src/clock.s: src/clock.cpp.s

.PHONY : src/clock.s

# target to generate assembly for a file
src/clock.cpp.s:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/clock.cpp.s
.PHONY : src/clock.cpp.s

src/common.o: src/common.cpp.o

.PHONY : src/common.o

# target to build an object file
src/common.cpp.o:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/common.cpp.o
.PHONY : src/common.cpp.o

src/common.i: src/common.cpp.i

.PHONY : src/common.i

# target to preprocess a source file
src/common.cpp.i:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/common.cpp.i
.PHONY : src/common.cpp.i

src/common.s: src/common.cpp.s

.PHONY : src/common.s

# target to generate assembly for a file
src/common.cpp.s:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/common.cpp.s
.PHONY : src/common.cpp.s

src/document.o: src/document.cpp.o

.PHONY : src/document.o

# target to build an object file
src/document.cpp.o:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/document.cpp.o
.PHONY : src/document.cpp.o

src/document.i: src/document.cpp.i

.PHONY : src/document.i

# target to preprocess a source file
src/document.cpp.i:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/document.cpp.i
.PHONY : src/document.cpp.i

src/document.s: src/document.cpp.s

.PHONY : src/document.s

# target to generate assembly for a file
src/document.cpp.s:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/document.cpp.s
.PHONY : src/document.cpp.s

src/full_adder.o: src/full_adder.cpp.o

.PHONY : src/full_adder.o

# target to build an object file
src/full_adder.cpp.o:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/full_adder.cpp.o
.PHONY : src/full_adder.cpp.o

src/full_adder.i: src/full_adder.cpp.i

.PHONY : src/full_adder.i

# target to preprocess a source file
src/full_adder.cpp.i:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/full_adder.cpp.i
.PHONY : src/full_adder.cpp.i

src/full_adder.s: src/full_adder.cpp.s

.PHONY : src/full_adder.s

# target to generate assembly for a file
src/full_adder.cpp.s:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/full_adder.cpp.s
.PHONY : src/full_adder.cpp.s

src/iface.o: src/iface.cpp.o

.PHONY : src/iface.o

# target to build an object file
src/iface.cpp.o:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/iface.cpp.o
.PHONY : src/iface.cpp.o

src/iface.i: src/iface.cpp.i

.PHONY : src/iface.i

# target to preprocess a source file
src/iface.cpp.i:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/iface.cpp.i
.PHONY : src/iface.cpp.i

src/iface.s: src/iface.cpp.s

.PHONY : src/iface.s

# target to generate assembly for a file
src/iface.cpp.s:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/iface.cpp.s
.PHONY : src/iface.cpp.s

src/logic_device.o: src/logic_device.cpp.o

.PHONY : src/logic_device.o

# target to build an object file
src/logic_device.cpp.o:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/logic_device.cpp.o
.PHONY : src/logic_device.cpp.o

src/logic_device.i: src/logic_device.cpp.i

.PHONY : src/logic_device.i

# target to preprocess a source file
src/logic_device.cpp.i:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/logic_device.cpp.i
.PHONY : src/logic_device.cpp.i

src/logic_device.s: src/logic_device.cpp.s

.PHONY : src/logic_device.s

# target to generate assembly for a file
src/logic_device.cpp.s:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/logic_device.cpp.s
.PHONY : src/logic_device.cpp.s

src/no_devices.o: src/no_devices.cpp.o

.PHONY : src/no_devices.o

# target to build an object file
src/no_devices.cpp.o:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/no_devices.cpp.o
.PHONY : src/no_devices.cpp.o

src/no_devices.i: src/no_devices.cpp.i

.PHONY : src/no_devices.i

# target to preprocess a source file
src/no_devices.cpp.i:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/no_devices.cpp.i
.PHONY : src/no_devices.cpp.i

src/no_devices.s: src/no_devices.cpp.s

.PHONY : src/no_devices.s

# target to generate assembly for a file
src/no_devices.cpp.s:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/no_devices.cpp.s
.PHONY : src/no_devices.cpp.s

src/not_device.o: src/not_device.cpp.o

.PHONY : src/not_device.o

# target to build an object file
src/not_device.cpp.o:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/not_device.cpp.o
.PHONY : src/not_device.cpp.o

src/not_device.i: src/not_device.cpp.i

.PHONY : src/not_device.i

# target to preprocess a source file
src/not_device.cpp.i:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/not_device.cpp.i
.PHONY : src/not_device.cpp.i

src/not_device.s: src/not_device.cpp.s

.PHONY : src/not_device.s

# target to generate assembly for a file
src/not_device.cpp.s:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/not_device.cpp.s
.PHONY : src/not_device.cpp.s

src/or_device.o: src/or_device.cpp.o

.PHONY : src/or_device.o

# target to build an object file
src/or_device.cpp.o:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/or_device.cpp.o
.PHONY : src/or_device.cpp.o

src/or_device.i: src/or_device.cpp.i

.PHONY : src/or_device.i

# target to preprocess a source file
src/or_device.cpp.i:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/or_device.cpp.i
.PHONY : src/or_device.cpp.i

src/or_device.s: src/or_device.cpp.s

.PHONY : src/or_device.s

# target to generate assembly for a file
src/or_device.cpp.s:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/or_device.cpp.s
.PHONY : src/or_device.cpp.s

src/or_not_device.o: src/or_not_device.cpp.o

.PHONY : src/or_not_device.o

# target to build an object file
src/or_not_device.cpp.o:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/or_not_device.cpp.o
.PHONY : src/or_not_device.cpp.o

src/or_not_device.i: src/or_not_device.cpp.i

.PHONY : src/or_not_device.i

# target to preprocess a source file
src/or_not_device.cpp.i:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/or_not_device.cpp.i
.PHONY : src/or_not_device.cpp.i

src/or_not_device.s: src/or_not_device.cpp.s

.PHONY : src/or_not_device.s

# target to generate assembly for a file
src/or_not_device.cpp.s:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/or_not_device.cpp.s
.PHONY : src/or_not_device.cpp.s

src/or_not_device3.o: src/or_not_device3.cpp.o

.PHONY : src/or_not_device3.o

# target to build an object file
src/or_not_device3.cpp.o:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/or_not_device3.cpp.o
.PHONY : src/or_not_device3.cpp.o

src/or_not_device3.i: src/or_not_device3.cpp.i

.PHONY : src/or_not_device3.i

# target to preprocess a source file
src/or_not_device3.cpp.i:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/or_not_device3.cpp.i
.PHONY : src/or_not_device3.cpp.i

src/or_not_device3.s: src/or_not_device3.cpp.s

.PHONY : src/or_not_device3.s

# target to generate assembly for a file
src/or_not_device3.cpp.s:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/or_not_device3.cpp.s
.PHONY : src/or_not_device3.cpp.s

src/or_not_device4.o: src/or_not_device4.cpp.o

.PHONY : src/or_not_device4.o

# target to build an object file
src/or_not_device4.cpp.o:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/or_not_device4.cpp.o
.PHONY : src/or_not_device4.cpp.o

src/or_not_device4.i: src/or_not_device4.cpp.i

.PHONY : src/or_not_device4.i

# target to preprocess a source file
src/or_not_device4.cpp.i:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/or_not_device4.cpp.i
.PHONY : src/or_not_device4.cpp.i

src/or_not_device4.s: src/or_not_device4.cpp.s

.PHONY : src/or_not_device4.s

# target to generate assembly for a file
src/or_not_device4.cpp.s:
	$(MAKE) -f CMakeFiles/logic_monitor.dir/build.make CMakeFiles/logic_monitor.dir/src/or_not_device4.cpp.s
.PHONY : src/or_not_device4.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... logic_monitor"
	@echo "... edit_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/adder64.o"
	@echo "... src/adder64.i"
	@echo "... src/adder64.s"
	@echo "... src/and_device.o"
	@echo "... src/and_device.i"
	@echo "... src/and_device.s"
	@echo "... src/and_not_device.o"
	@echo "... src/and_not_device.i"
	@echo "... src/and_not_device.s"
	@echo "... src/and_not_device3.o"
	@echo "... src/and_not_device3.i"
	@echo "... src/and_not_device3.s"
	@echo "... src/and_not_device4.o"
	@echo "... src/and_not_device4.i"
	@echo "... src/and_not_device4.s"
	@echo "... src/carry4.o"
	@echo "... src/carry4.i"
	@echo "... src/carry4.s"
	@echo "... src/carry64.o"
	@echo "... src/carry64.i"
	@echo "... src/carry64.s"
	@echo "... src/clock.o"
	@echo "... src/clock.i"
	@echo "... src/clock.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/document.o"
	@echo "... src/document.i"
	@echo "... src/document.s"
	@echo "... src/full_adder.o"
	@echo "... src/full_adder.i"
	@echo "... src/full_adder.s"
	@echo "... src/iface.o"
	@echo "... src/iface.i"
	@echo "... src/iface.s"
	@echo "... src/logic_device.o"
	@echo "... src/logic_device.i"
	@echo "... src/logic_device.s"
	@echo "... src/no_devices.o"
	@echo "... src/no_devices.i"
	@echo "... src/no_devices.s"
	@echo "... src/not_device.o"
	@echo "... src/not_device.i"
	@echo "... src/not_device.s"
	@echo "... src/or_device.o"
	@echo "... src/or_device.i"
	@echo "... src/or_device.s"
	@echo "... src/or_not_device.o"
	@echo "... src/or_not_device.i"
	@echo "... src/or_not_device.s"
	@echo "... src/or_not_device3.o"
	@echo "... src/or_not_device3.i"
	@echo "... src/or_not_device3.s"
	@echo "... src/or_not_device4.o"
	@echo "... src/or_not_device4.i"
	@echo "... src/or_not_device4.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

